on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_PASSWORD }}
          docker build -t leobgs/leocinema-frontend:testing .
          docker push leobgs/leocinema-frontend:testing
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Clone do Repositório do ArgoCD
        run: |
          git clone https://github.com/Ll2223/leocinema-helm.git
      # Substitua "seu-usuario" pelo seu nome de usuário e "seu-repositorio-argo" pelo nome do repositório gerenciado pelo ArgoCD.

      - name: Atualizar arquivo values.yaml
        run: |
          sed -i 's/leocinema-frontend:.*/leocinema-frontend:testing/' leocinema-helm/leocinema/values.yaml
      # Substitua "seu-repositorio-argo" pelo diretório do repositório do ArgoCD e "caminho_para_seu_arquivo/values.yaml" pelo caminho correto do arquivo values.yaml.

      - name: Commit e Push das Alterações para o Repositório do ArgoCD
        run: |
          cd leocinema-helm
          git config --local user.email "you@example.com"
          git config --local user.name "GitHub Actions"
          git add leocinema/values.yaml
          git commit -m "Atualização automática da tag da imagem Docker"
          git push https://${{ secrets.ARGOCD_TOKEN }}@github.com/Ll2223/leocinema-helm.git
      # Substitua "seu-repositorio-argo" pelo diretório do repositório do ArgoCD e "caminho_para_seu_arquivo/values.yaml" pelo caminho correto do arquivo values.yaml.
